package com.globbypotato.rockhounding_rocks.enums.rocks;

public enum EnumRockList implements BaseEnum{
	BLACK_AVENTURINE,
	BASANITE,
	BLACK_GRANITE,
	JET,
	LUXULYANITE,
	BLACK_ONYX,
	PORTORO,
	SNOWFLAKE_OBSIDIAN,
	BLACK_TIGER_EYE,
	SLATE,
	GABBRO,
	BLUE_AVENTURINE,
	CHRYSOCOLLA,
	BLUE_GRANITE,
	BLUE_JASPER,
	LABRADORITE,
	LARIMAR,
	BLUE_ONYX,
	PIETERSITE,
	SODALITE,
	BLUE_TIGER_EYE,
	AZURITE,
	BROWN_AVENTURINE,
	LATERITE,
	BROWN_CARNELIAN,
	BROWN_PORPHYRY,
	SCORIA,
	SMOKY_QUARTZ,
	BRONZITE,
	TIGER_IRON,
	ARKOSE,
	IGNIMBRITE,
	GNEISS,
	PUMICE,
	GRAY_GRANITE,
	GRAY_ONYX,
	GRAY_PORPHYRY,
	SPIDERWEB_JASPER,
	GRAY_TRACHYTE,
	GRAY_TRAVERTINE,
	GRAY_TUFF,
	ZEBRA_JASPER,
	DACITE,
	MIGMATITE,
	AMAZONITE,
	GREEN_AVENTURINE,
	GREEN_GRANITE,
	GREEN_ONYX,
	GREEN_PORPHYRY,
	GREEN_JASPER,
	BLOODSTONE,
	JADEITE,
	MALACHITE,
	SERPENTINITE,
	ZOISITE,
	GREEN_TIGER_EYE,
	GREEN_TUFF,
	UNAKITE,
	CHRYSOPRASE,
	RAINFOREST_JASPER,
	GLAUCONITE,
	DUNITE,
	RHODOCHROSITE,
	KAKORTOKITE,
	PINK_GRANITE,
	PINK_ONYX,
	PINK_TRACHYTE,
	PINK_PORPHYRY,
	PINK_TRAVERTINE,
	RHODONITE,
	CHAROITE,
	JASPEROID,
	SUGILITE,
	STICHTITE,
	DUMORTIERITE,
	PURPLE_PORPHYRY,
	APLITE,
	RED_CARNELIAN,
	RED_AVENTURINE,
	RED_GRANITE,
	RED_ONYX,
	RED_PORPHYRY,
	RED_JASPER,
	ROSE_RED,
	SUNSTONE,
	RED_TRACHYTE,
	NOREENA_JASPER,
	MOOKAITE_JASPER,
	RED_TIGER_EYE,
	JASPILITE,
	ALABASTER,
	CHALK,
	WHITE_GRANITE,
	WHITE_ONYX,
	MOONSTONE,
	PORCELAIN_JASPER,
	MILKY_QUARTZ,
	WHITE_TUFF,
	OCEAN_JASPER,
	HOWLITE,
	DALMATIAN_JASPER,
	DIATOMITE,
	YELLOW_AVENTURINE,
	YELLOW_GRANITE,
	YELLOW_JASPER,
	YELLOW_ONYX,
	YELLOW_PORPHYRY,
	YELLOW_TIGER_EYE,
	YELLOW_TRACHYTE,
	YELLOW_TUFF,
	MUDSTONE,
	FELSITE;

	//---------CUSTOM----------------
	public static int size(){
		return values().length;
	}

	public static String name(int index) {
		return values()[index].getName();
	}

	//---------ENUM----------------
	public static String[] getNames(){
		String[] temp = new String[size()];
		for(int i = 0; i < size(); i++){
			temp[i] = getDysplayName(i);
		}
		return temp;
	}

	public static String getDysplayName(int index){
		return name(index);
	}

}